### ISSUE TITLE
Running coap-server on an ipv6 address

### ISSUE THREAD

**Issue by dh1105** [Tanganelli/CoAPthon#115]
I am trying to run a coap server using an ipv6 address but I am unable to do that with any ipv6 address other than localhost ([::1]). What could be the cause of this and how could I start the server on an ipv6 address?

**Comment by Tanganelli** [comment]
Can you add the output of the server along with the command that you use to
start the server? Moreover if it is possible even the output of
ifconfig may be useful.

Il giorno mar 12 giu 2018 alle ore 15:47 Dhruv Verma <
notifications@github.com> ha scritto:

**Comment by dh1105** [comment]
Output of ifconfig:

```
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.103.140  netmask 255.255.255.0  broadcast 192.168.103.255
        inet6 fe80::a00:27ff:fe97:e9d  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:97:0e:9d  txqueuelen 1000  (Ethernet)
        RX packets 9408  bytes 4296046 (4.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3845  bytes 619173 (619.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 9743  bytes 9317967 (9.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9743  bytes 9317967 (9.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::7878:56ff:fe2a:e8c6  prefixlen 64  scopeid 0x20<link>
        ether 7a:78:56:2a:e8:c6  txqueuelen 1000  (Ethernet)
        RX packets 125  bytes 9038 (9.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 129  bytes 13503 (13.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

The output of the server:
```
Traceback (most recent call last):
  File "/home/riot/CoAPthon/server_eg.py", line 108, in <module>
    main()
  File "/home/riot/CoAPthon/server_eg.py", line 100, in main
    server = CoAPServer(ip, port, multicast)
  File "/home/riot/CoAPthon/server_eg.py", line 90, in __init__
    CoAP.__init__(self, (host, port), multicast)
  File "/home/riot/CoAPthon/coapthon/server/coap.py", line 120, in __init__
    self._socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
```

Server running ipv6 address is: 

> fe80::a00:27ff:fe97:e9d

>

**Comment by Tanganelli** [comment]
Honestly, I don't know what is going on. You may try to figure out through the debugger the value of self.server_address.

**Comment by Dimaqa** [comment]
My ip -a looks like this:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 12:e9:bd:12:40:1c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.50/24 brd 192.168.1.255 scope global eth0
    inet6 fd00::10e9:bdff:fe12:401c/64 scope global dynamic
       valid_lft 2591867sec preferred_lft 604667sec
    inet6 fe80::10e9:bdff:fe12:401c/64 scope link
       valid_lft forever preferred_lft forever
8: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/ether 12:e9:bd:12:40:1c brd ff:ff:ff:ff:ff:ff
    inet 10.8.0.33/16 brd 10.8.255.255 scope global tap0
    inet6 fd00::10e9:bdff:fe12:401c/64 scope global dynamic
       valid_lft 2591703sec preferred_lft 604503sec
    inet6 fe80::10e9:bdff:fe12:401c/64 scope link
       valid_lft forever preferred_lft forever
```
I guess it's not coapthon problem. You are trying to use link-local adress. Did you try to ping it? Because
I can't:  
ping6 fe80::10e9:bdff:fe12:401c
connect: Invalid argument
I am hosting server on server = CoAPServer('::', 5683). And its working fine with fd00::10e9:bdff:fe12:401c and  even with 
ipv4 192.168.1.50, but not with fe80.
